apiVersion: apps/v1
kind: ReplicationController # ReplicationController is deprecated in v1.16+ better to use ReplicaSet now
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    project: nginx
  template:
    metadata:
      name: nginx
      labels:
        project: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80