apiVersion: v1
kind: Pod
metadata:
  name: ebs-app
spec:
  containers:
    - name: ebs-app
      image: centos
      command: ["/bin/sh", "-c", "while true; do echo 'Hello from EBS-backed Pod' > /data/ebs-test.txt; sleep 5; done"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-claim