apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-preferred
  labels:
    project: website
    environment: development
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube-m04
        - weight: 2
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube-m02
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
