apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  labels:
    project: website
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
