apiVersion: v1
kind: Pod
metadata:
    name: nginx-secrets-mount-envvar
spec:
    containers:
    - name: nginx
      image: nginx
      env:
      - name: SECRET-USERNAME
        valueFrom:
          secretKeyRef:
            name: creds
            key: username.txt
      - name: SECRET-PASSWORD
        valueFrom:
          secretKeyRef:
            name: creds
            key: password.txt