apiVersion: v1
kind: Pod
metadata:
    name: nginx-secrets-mount
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/nginx/secrets
        readOnly: true
    volumes:
    - name: secret-volume
      secret:
        secretName: creds