apiVersion: v1
kind: Pod
metadata:
    name: nginx-secrets-mount
spec:
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/nginx/secrets
        readOnly: true
    volumes:
    - name: secret-volume
      secret:
        secretName: creds