apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-volume-common
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "web-volume-common"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: common
        persistentVolumeClaim:
          claimName: www-common
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-web-volume
          mountPath: /data
        - name: common
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www-web-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi
