apiVersion: v1
kind: Pod
metadata:
    name: nginx-cm-literal
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
      - name: foo
        value: bar
      - name: ENVIRONMENT-TEST
        valueFrom:
          configMapKeyRef:
            name: test-cm
            key: variable1