apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: website
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
