apiVersion: v1
kind: Pod
metadata:
  name: liveness-cmd
  labels:
    app: liveness
spec:
  containers:
    - name: liveness
      image: nginx:latest
      livenessProbe:
        exec:
          command:
            - curl
            - localhost
        initialDelaySeconds: 20
        periodSeconds: 5
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"