apiVersion: v1
kind: Pod
metadata:
  name: readiness-http
  labels:
    app: readiness
spec:
  containers:
    - name: readiness
      image: nginx:latest
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"