apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vcc-eksctl
  region: us-west-2

managedNodeGroups:
  - name: ng-1-asg
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    iam:
      withAddonPolicies:
        autoScaler: true